:- module(psl, [
    publicSuffix/1
]).

% THIS IS INCOMPLETE BY DESIGN. THE ACTUAL LIST IS HUGE.

publicSuffix("uk").
publicSuffix("ac.uk").
publicSuffix("co.uk").
publicSuffix("gov.uk").
publicSuffix("ltd.uk").
publicSuffix("me.uk").
publicSuffix("net.uk").
publicSuffix("nhs.uk").
publicSuffix("org.uk").
publicSuffix("plc.uk").
publicSuffix("police.uk").
publicSuffix("ch.uk").
publicSuffix("us").
publicSuffix("dni.us").
publicSuffix("fed.us").
publicSuffix("isa.us").
publicSuffix("kids.us").
publicSuffix("nsn.us").
publicSuffix("ak.us").
publicSuffix("al.us").
publicSuffix("ar.us").
publicSuffix("as.us").
publicSuffix("az.us").
publicSuffix("ca.us").
publicSuffix("co.us").
publicSuffix("ct.us").
publicSuffix("dc.us").
publicSuffix("de.us").
publicSuffix("fl.us").
publicSuffix("ga.us").
publicSuffix("gu.us").
publicSuffix("hi.us").
publicSuffix("ia.us").
publicSuffix("id.us").
publicSuffix("il.us").
publicSuffix("in.us").
publicSuffix("ks.us").
publicSuffix("ky.us").
publicSuffix("la.us").
publicSuffix("ma.us").
publicSuffix("md.us").
publicSuffix("me.us").
publicSuffix("mi.us").
publicSuffix("mn.us").
publicSuffix("mo.us").
publicSuffix("ms.us").
publicSuffix("mt.us").
publicSuffix("nc.us").
publicSuffix("nd.us").
publicSuffix("ne.us").
publicSuffix("nh.us").
publicSuffix("nj.us").
publicSuffix("nm.us").
publicSuffix("nv.us").
publicSuffix("ny.us").
publicSuffix("oh.us").
publicSuffix("ok.us").
publicSuffix("or.us").
publicSuffix("pa.us").
publicSuffix("pr.us").
publicSuffix("ri.us").
publicSuffix("sc.us").
publicSuffix("sd.us").
publicSuffix("tn.us").
publicSuffix("tx.us").
publicSuffix("ut.us").
publicSuffix("vi.us").
publicSuffix("vt.us").
publicSuffix("va.us").
publicSuffix("wa.us").
publicSuffix("wi.us").
publicSuffix("wv.us").
publicSuffix("wy.us").
publicSuffix("k12.ak.us").
publicSuffix("k12.al.us").
publicSuffix("k12.ar.us").
publicSuffix("k12.as.us").
publicSuffix("k12.az.us").
publicSuffix("k12.ca.us").
publicSuffix("k12.co.us").
publicSuffix("k12.ct.us").
publicSuffix("k12.dc.us").
publicSuffix("k12.de.us").
publicSuffix("k12.fl.us").
publicSuffix("k12.ga.us").
publicSuffix("k12.gu.us").
publicSuffix("k12.ia.us").
publicSuffix("k12.id.us").
publicSuffix("k12.il.us").
publicSuffix("k12.in.us").
publicSuffix("k12.ks.us").
publicSuffix("k12.ky.us").
publicSuffix("k12.la.us").
publicSuffix("k12.ma.us").
publicSuffix("k12.md.us").
publicSuffix("k12.me.us").
publicSuffix("k12.mi.us").
publicSuffix("k12.mn.us").
publicSuffix("k12.mo.us").
publicSuffix("k12.ms.us").
publicSuffix("k12.mt.us").
publicSuffix("k12.nc.us").
publicSuffix("k12.ne.us").
publicSuffix("k12.nh.us").
publicSuffix("k12.nj.us").
publicSuffix("k12.nm.us").
publicSuffix("k12.nv.us").
publicSuffix("k12.ny.us").
publicSuffix("k12.oh.us").
publicSuffix("k12.ok.us").
publicSuffix("k12.or.us").
publicSuffix("k12.pa.us").
publicSuffix("k12.pr.us").
publicSuffix("k12.sc.us").
publicSuffix("k12.tn.us").
publicSuffix("k12.tx.us").
publicSuffix("k12.ut.us").
publicSuffix("k12.vi.us").
publicSuffix("k12.vt.us").
publicSuffix("k12.va.us").
publicSuffix("k12.wa.us").
publicSuffix("k12.wi.us").
publicSuffix("k12.wy.us").
publicSuffix("cc.ak.us").
publicSuffix("cc.al.us").
publicSuffix("cc.ar.us").
publicSuffix("cc.as.us").
publicSuffix("cc.az.us").
publicSuffix("cc.ca.us").
publicSuffix("cc.co.us").
publicSuffix("cc.ct.us").
publicSuffix("cc.dc.us").
publicSuffix("cc.de.us").
publicSuffix("cc.fl.us").
publicSuffix("cc.ga.us").
publicSuffix("cc.gu.us").
publicSuffix("cc.hi.us").
publicSuffix("cc.ia.us").
publicSuffix("cc.id.us").
publicSuffix("cc.il.us").
publicSuffix("cc.in.us").
publicSuffix("cc.ks.us").
publicSuffix("cc.ky.us").
publicSuffix("cc.la.us").
publicSuffix("cc.ma.us").
publicSuffix("cc.md.us").
publicSuffix("cc.me.us").
publicSuffix("cc.mi.us").
publicSuffix("cc.mn.us").
publicSuffix("cc.mo.us").
publicSuffix("cc.ms.us").
publicSuffix("cc.mt.us").
publicSuffix("cc.nc.us").
publicSuffix("cc.nd.us").
publicSuffix("cc.ne.us").
publicSuffix("cc.nh.us").
publicSuffix("cc.nj.us").
publicSuffix("cc.nm.us").
publicSuffix("cc.nv.us").
publicSuffix("cc.ny.us").
publicSuffix("cc.oh.us").
publicSuffix("cc.ok.us").
publicSuffix("cc.or.us").
publicSuffix("cc.pa.us").
publicSuffix("cc.pr.us").
publicSuffix("cc.ri.us").
publicSuffix("cc.sc.us").
publicSuffix("cc.sd.us").
publicSuffix("cc.tn.us").
publicSuffix("cc.tx.us").
publicSuffix("cc.ut.us").
publicSuffix("cc.vi.us").
publicSuffix("cc.vt.us").
publicSuffix("cc.va.us").
publicSuffix("cc.wa.us").
publicSuffix("cc.wi.us").
publicSuffix("cc.wv.us").
publicSuffix("cc.wy.us").
publicSuffix("lib.ak.us").
publicSuffix("lib.al.us").
publicSuffix("lib.ar.us").
publicSuffix("lib.as.us").
publicSuffix("lib.az.us").
publicSuffix("lib.ca.us").
publicSuffix("lib.co.us").
publicSuffix("lib.ct.us").
publicSuffix("lib.dc.us").
publicSuffix("lib.fl.us").
publicSuffix("lib.ga.us").
publicSuffix("lib.gu.us").
publicSuffix("lib.hi.us").
publicSuffix("lib.ia.us").
publicSuffix("lib.id.us").
publicSuffix("lib.il.us").
publicSuffix("lib.in.us").
publicSuffix("lib.ks.us").
publicSuffix("lib.ky.us").
publicSuffix("lib.la.us").
publicSuffix("lib.ma.us").
publicSuffix("lib.md.us").
publicSuffix("lib.me.us").
publicSuffix("lib.mi.us").
publicSuffix("lib.mn.us").
publicSuffix("lib.mo.us").
publicSuffix("lib.ms.us").
publicSuffix("lib.mt.us").
publicSuffix("lib.nc.us").
publicSuffix("lib.nd.us").
publicSuffix("lib.ne.us").
publicSuffix("lib.nh.us").
publicSuffix("lib.nj.us").
publicSuffix("lib.nm.us").
publicSuffix("lib.nv.us").
publicSuffix("lib.ny.us").
publicSuffix("lib.oh.us").
publicSuffix("lib.ok.us").
publicSuffix("lib.or.us").
publicSuffix("lib.pa.us").
publicSuffix("lib.pr.us").
publicSuffix("lib.ri.us").
publicSuffix("lib.sc.us").
publicSuffix("lib.sd.us").
publicSuffix("lib.tn.us").
publicSuffix("lib.tx.us").
publicSuffix("lib.ut.us").
publicSuffix("lib.vi.us").
publicSuffix("lib.vt.us").
publicSuffix("lib.va.us").
publicSuffix("lib.wa.us").
publicSuffix("lib.wi.us").
publicSuffix("lib.wy.us").
publicSuffix("pvt.k12.ma.us").
publicSuffix("chtr.k12.ma.us").
publicSuffix("paroch.k12.ma.us").
publicSuffix("ann-arbor.mi.us").
publicSuffix("cog.mi.us").
publicSuffix("dst.mi.us").
publicSuffix("eaton.mi.us").
publicSuffix("gen.mi.us").
publicSuffix("mus.mi.us").
publicSuffix("tec.mi.us").
publicSuffix("washtenaw.mi.us").
